name: CI
on:
  push:
    branches:
      - feat-setup-docs-site-web-app
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      ## Build

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # An action that sets the base and head SHAs used by nx affected commands
      # Docs: https://github.com/nrwl/nx-set-shas
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
          set-environment-variables-for-job: true
          last-successful-event: 'push'
          error-on-no-successful-workflow: false
          working-directory: '.'

      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --target=build --parallel=3

      ## Deploy

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./apps/docs-site-web/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
